module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('orders', [
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Кебаб',
        img: '/src/kebab.jpeg',
        location: 'Лондон',
        discription: 'Самый вкусный околосвежий кэбаб! Бери щас же, а то скушою!!!',
        price: 82,
        saleprice: 45,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Пицца',
        img: '/src/pizza.jpeg',
        location: 'Осло',
        discription: 'Пицца неплохая, хотя, лично я, к грибам не оч, но ты бери.',
        price: 72,
        saleprice: 25,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Бургеры',
        img: '/src/burger.jpeg',
        location: 'Париж',
        discription: 'Бургеры бомба! Как бигтейсти, только лучше.',
        price: 92,
        saleprice: 35,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Суп',
        img: '/src/supec.jpeg',
        location: 'Петербург',
        discription: 'Скушай супчик и сразу откроется третий глаз!',
        price: 52,
        saleprice: 45,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Паста Пупсянара',
        img: '/src/pasta.jpeg',
        location: 'Новгород',
        discription: 'Горячая паста, почти никто ее не ел, вполне можно заморить червячка.',
        price: 520,
        saleprice: 459,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Салат Цезарь',
        img: '/src/cezar.jpeg',
        location: 'Гравити Фолз',
        discription: 'Очень вкусный салат, совсем не пожух и пахнет только курицей и ничем больше, даже если кажется обратное!',
        price: 32,
        saleprice: 15,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Роллы',
        img: '/src/rolls.jpeg',
        location: 'Хогсмид',
        discription: 'Внимание-внимание!!! Роллы не из файвтерочки(пятерочки)! Повторяю, не из пятерочки! Оч вкусно - бери!',
        price: 57,
        saleprice: 41,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { // указываем название модели и прокидываем наши значения колонок
        title: 'Шварма',
        img: '/src/shava.jpeg',
        location: 'Нитландия',
        discription: 'Ну, с шавухой, думаю, итак все понятно! Оч вкусно и стыно! P.S. Руки во время готовки не мыли',
        price: 78,
        saleprice: 46,
        admin_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('orders', null, {});
  },
};
